/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";

export default function Hamburguer(props) {
    
    const hamburguerRef = useRef(null)
    const hamburguer = useGLTF("/static/hamburger.glb");
    return (
        <>
        <group>
        <Html>
            <iframe width="100" height="100" 
            src="https://www.youtube.com/embed/XNor6Zg1chA" 
            title="¿Qué es lo que realmente no entiendes?" 
            frameborder="0" 
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </Html>
        <primitive 
            object={hamburguer.scene}
            ref={hamburguerRef}
            {...props} 
            dispose={null} 
        />

        
        </group>
        </>
        
    );
}

useGLTF.preload("/static/hamburger.glb");
